name: SQL Services status
on:
    workflow_dispatch: 
jobs: 
    check-SQL-service:
        runs-on: self-hosted
        steps:
            - name: check status
              uses: actions/checkout@v4

            - name: Check SQL Service
              shell: powershell
              run: |
                $servers =@(
                  "SWATHI",
                  "SANVIKA"
                  )
                  foreach ($server in $servers){
                   write-host "Computer Name : $server"
                   invoke-command -computername $server -scriptblock {
                   Get-service -name "*sql*" -computername $server |select DisplayName, Name, Status
                    }|out-file "\\SREE\E$\sql_status.txt"
                  } 
              env: 
                SQL_USER: ${{ secrets.SQL_USER}}
                SQL_PASSWORD: ${{ secrets.SQL_PASSWORD}}
          

